require_relative '../app/models/car'
require_relative '../app/models/lot'
require_relative '../app/models/slot'
require_relative '../app/service/command_dispatcher'
require_relative '../app/controllers/parking_controller'
